### ISSUE TITLE
gbp import-orig

### ISSUE THREAD

**Issue by grammoboy2** [lvm/build-supercollider#11]
Could you give a example of how this command should look like exactly for version 3.11?

gbp import-orig --pristine-tar --sign-tags ${path-to-fetched-tarball}

**Comment by lvm** [comment]
That's a pretty old script based on [this blog spot](http://mcld.co.uk/blog/2017/how-to-package-supercollider-for-debian-and-ubuntu-linux.html) so in any case, you should ask him or check the Debian developer documentation.
