### ISSUE TITLE
Can't finish building: Makefile:162: recipe for target 'all' failed

### ISSUE THREAD

**Issue by a-moreira** [lvm/build-supercollider#12]
Below is the output I get when I do
`sh build-supercollider.sh`

**Hit:1 http://br.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]    
Ign:5 http://ppa.launchpad.net/cran/imagemagick/ubuntu bionic InRelease        
Hit:6 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ InRelease    
Hit:7 http://ppa.launchpad.net/cran/poppler/ubuntu bionic InRelease            
Hit:8 http://ppa.launchpad.net/elementary-add-team/icons/ubuntu bionic InRelease
Hit:9 http://ppa.launchpad.net/elementary-os/daily/ubuntu bionic InRelease     
Ign:10 https://deb.torproject.org/torproject.org hera InRelease                
Err:11 https://deb.torproject.org/torproject.org hera Release                  
  404  Not Found [IP: 116.202.120.166 443]
Hit:12 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease
Hit:13 http://ppa.launchpad.net/gnome3-team/gnome3/ubuntu bionic InRelease     
Hit:14 http://ppa.launchpad.net/gnome3-team/gnome3-staging/ubuntu bionic InRelease
Hit:15 http://ppa.launchpad.net/linrunner/tlp/ubuntu bionic InRelease          
Ign:16 http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu bionic InRelease
Hit:17 http://ppa.launchpad.net/noobslab/icons/ubuntu bionic InRelease
Hit:18 http://ppa.launchpad.net/noobslab/themes/ubuntu bionic InRelease        
Hit:19 http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu bionic InRelease
Err:20 http://ppa.launchpad.net/cran/imagemagick/ubuntu bionic Release         
  404  Not Found [IP: 91.189.95.83 80]
Err:21 http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                                  
E: The repository 'https://deb.torproject.org/torproject.org hera Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/cran/imagemagick/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.4ubuntu1).
emacs is already the newest version (47.0).
libfftw3-dev is already the newest version (3.3.7-1).
libjack-jackd2-dev is already the newest version (1.9.12~dfsg-2).
libqt5svg5-dev is already the newest version (5.9.5-0ubuntu1).
libreadline-dev is already the newest version (7.0-3).
libxt-dev is already the newest version (1:1.1.5-1).
pkg-config is already the newest version (0.29.1-0ubuntu2).
libcwiid-dev is already the newest version (0.6.00+svn201-4).
libqt5sensors5-dev is already the newest version (5.9.5-0ubuntu1).
libqt5webkit5-dev is already the newest version (5.212.0~alpha2-7ubuntu1).
libqt5websockets5-dev is already the newest version (5.9.5-0ubuntu1).
qtpositioning5-dev is already the newest version (5.9.5+dfsg-0ubuntu2).
qttools5-dev is already the newest version (5.9.5-0ubuntu1).
qttools5-dev-tools is already the newest version (5.9.5-0ubuntu1).
qtwebengine5-dev is already the newest version (5.9.5+dfsg-0ubuntu2).
subversion is already the newest version (1.9.7-4ubuntu1).
cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).
git is already the newest version (1:2.17.1-1ubuntu0.5).
libasound2-dev is already the newest version (1.1.3-5ubuntu0.4).
libavahi-client-dev is already the newest version (0.7-3.1ubuntu1.2).
libicu-dev is already the newest version (60.2-3ubuntu3.1).
libqt5opengl5-dev is already the newest version (5.9.5+dfsg-0ubuntu2.5).
libsndfile1-dev is already the newest version (1.0.28-4ubuntu0.18.04.1).
libudev-dev is already the newest version (237-3ubuntu10.39).
qt5-qmake is already the newest version (5.9.5+dfsg-0ubuntu2.5).
qt5-default is already the newest version (5.9.5+dfsg-0ubuntu2.5).
qtdeclarative5-dev is already the newest version (5.9.5-0ubuntu1.1).
The following package was automatically installed and is no longer required:
  supercollider-supernova
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
fatal: destination path '/tmp/supercollider' already exists and is not an empty directory.
-- SuperCollider Version: 3.11.0
-- Building from branch 3.11, commit hash is 244e98bda
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- Using bundled boost
-- Using bundled yaml-cpp
-- HIDAPI components:
--     linux hidraw
-- libudev stable: 1
-- Found UDev: /lib/x86_64-linux-gnu/libudev.so
--    include: /usr/include
--     hidapi_parser
-- Building with HID support
-- Using fftw3f
-- Found jack: /usr/lib/x86_64-linux-gnu/libjack.so
-- Audio API: jack
-- Found GNU Readline version 7.0: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Found Qt: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.5
-- sclang: Building with QtWebEngine
-- Compiling with Ableton Link support
-- Compiling with Readline support
-- Compiling with ALSA midi support
-- Building the Qt IDE
-- IDE: Building with QtWebEngine
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/supercollider/build
[  0%] Built target hidapi
[  0%] Built target hidapi_parser
[  1%] Built target boost_system_lib
[  3%] Built target ML_UGens_supernova
[  4%] Built target FFT_UGens_supernova
[  4%] Built target UnpackFFTUGens_supernova
[  5%] Built target UnaryOpUGens_supernova
[  5%] Built target TestUGens_supernova
[  5%] Built target PhysicalModelingUGens_supernova
[  5%] Built target NoiseUGens_supernova
[  6%] Built target OscUGens_supernova
[  7%] Built target FFT_UGens
[  7%] Built target UnpackFFTUGens
[  8%] Built target GendynUGens
[  8%] Built target MulAddUGens
[  8%] Built target IOUGens
[  8%] Built target FilterUGens
[  8%] Built target ChaosUGens
[  8%] Built target GendynUGens_supernova
[  9%] Built target PV_ThirdParty_supernova
[  9%] Built target DelayUGens
[  9%] Built target OscUGens
[  9%] Built target BinaryOpUGens
[ 10%] Built target TriggerUGens_supernova
[ 10%] Built target DynNoiseUGens_supernova
[ 11%] Built target PanUGens
[ 11%] Built target LFUGens
[ 11%] Built target GrainUGens
[ 13%] Built target DemandUGens
[ 13%] Built target ChaosUGens_supernova
[ 13%] Built target UnaryOpUGens
[ 13%] Built target PhysicalModelingUGens
[ 14%] Built target TestUGens
[ 14%] Built target DynNoiseUGens
[ 14%] Built target TriggerUGens
[ 15%] Built target PanUGens_supernova
[ 15%] Built target NoiseUGens
[ 15%] Built target PV_ThirdParty
[ 15%] Built target ReverbUGens_supernova
[ 16%] Built target ReverbUGens
[ 16%] Built target FilterUGens_supernova
[ 17%] Built target ML_UGens
[ 17%] Built target BinaryOpUGens_supernova
[ 18%] Built target GrainUGens_supernova
[ 18%] Built target DelayUGens_supernova
[ 18%] Built target DemandUGens_supernova
[ 19%] Built target LFUGens_supernova
[ 19%] Built target IOUGens_supernova
[ 19%] Built target MulAddUGens_supernova
[ 19%] Built target DiskIO_UGens
[ 19%] Built target tlsf
Scanning dependencies of target yaml
[ 19%] Built target oscpack
[ 19%] Building CXX object external_libraries/CMakeFiles/yaml.dir/libyamlcpp.cpp.o
[ 21%] Built target boost_filesystem_lib
[ 21%] Built target sclang.elc
[ 21%] Built target sclang-interp.elc
[ 23%] Built target boost_program_options_lib
[ 23%] Built target sclang-language.elc
[ 25%] Built target boost_regex_lib
[ 25%] Built target sclang-document.elc
[ 26%] Built target sclang-keys.elc
[ 26%] Creating byte-compiled Emacs lisp /tmp/supercollider/build/editors/sc-el/el/sclang-help.elc
[ 26%] Built target sclang-menu.elc
[ 26%] Built target sclang-dev.elc
[ 27%] Built target sclang-vars.elc
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
[ 27%] Built target sclang-minor-mode.elc
[ 27%] Built target sclang-mode.elc
[ 27%] Built target sclang-util.elc
[ 27%] Built target sclang-server.elc

In toplevel form:
sclang-help.el:86:7:Warning: assignment to free variable ‘w3m-use-filter’
sclang-help.el:89:18:Warning: reference to free variable ‘w3m-filter-rules’
sclang-help.el:89:18:Warning: assignment to free variable ‘w3m-filter-rules’
[ 27%] Built target sclang-browser.elc
[ 27%] Built target sclang-widgets.elc
sclang-help.el:261:1:Error: Symbol’s function definition is void: gensym
editors/sc-el/el/CMakeFiles/sclang-help.elc.dir/build.make:60: recipe for target 'editors/sc-el/el/sclang-help.elc' failed
make[2]: *** [editors/sc-el/el/sclang-help.elc] Error 1
CMakeFiles/Makefile2:3436: recipe for target 'editors/sc-el/el/CMakeFiles/sclang-help.elc.dir/all' failed
make[1]: *** [editors/sc-el/el/CMakeFiles/sclang-help.elc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target boost_test
Scanning dependencies of target boost_thread_lib
[ 27%] Building CXX object testsuite/server/CMakeFiles/boost_test.dir/boost_test.cpp.o
[ 27%] Building CXX object external_libraries/CMakeFiles/boost_thread_lib.dir/boost/libs/thread/src/future.cpp.o
[ 27%] Building CXX object external_libraries/CMakeFiles/boost_thread_lib.dir/boost/libs/thread/src/tss_null.cpp.o
[ 27%] Building CXX object external_libraries/CMakeFiles/boost_thread_lib.dir/boost/libs/thread/src/pthread/once.cpp.o
[ 28%] Building CXX object external_libraries/CMakeFiles/boost_thread_lib.dir/boost/libs/thread/src/pthread/once_atomic.cpp.o
[ 28%] Building CXX object external_libraries/CMakeFiles/boost_thread_lib.dir/boost/libs/thread/src/pthread/thread.cpp.o
[ 29%] Linking CXX static library libyaml.a
[ 29%] Built target yaml
[ 29%] Linking CXX static library libboost_thread_lib.a
[ 29%] Built target boost_thread_lib
[ 29%] Linking CXX static library libboost_test.a
[ 29%] Built target boost_test
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
**

**Comment by lvm** [comment]
That's a supercollider issue, not from this script.

**Comment by gtnbssn** [comment]
@a-moreira : edit build-supercollider.sh to have `-DSC_EL=OFF` (instead of ON), that did the trick for me (despite the script taking care of installing emacs, i had to disable this for the compilation to go through).
