### ISSUE TITLE
Thought you should know

### ISSUE THREAD

**Issue by daffyd-jones** [lvm/build-supercollider#14]
I was trying to install onto mint 19.2 and when I went to run the supercollider.sh i recieved the error below. I went to the repository and got a 404. 

 E: The repository 'http://apt.puredata.info/releases tina Release' does not have a Release file.

**Comment by lvm** [comment]
That's because you have broken repositories in your `/etc/apt/sources.list` or `/etc/apt/sources.list.d/*`. Completely unrelated to this script.
