### ISSUE TITLE
Fails to build on Ubuntu Bionic

### ISSUE THREAD

**Issue by stevemcc** [lvm/build-supercollider#16]
Failing to build with this error. Note the trailing slash in the URL; the correct URL for the sc emacs integration repo does not appear to have this trailing slash.

```
Cloning into '/tmp/supercollider/editors/sc-el'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://github.com/supercollider/scel/' into submodule path '/tmp/supercollider/editors/sc-el' failed
Failed to clone 'editors/sc-el' a second time, aborting
```

Full output: https://gist.github.com/stevemcc/e1de0d3c06e172a1b9e85248aa385782

**Comment by stevemcc** [comment]
Appears to be a supercollider issue - also happens following the compile instructions at their repo.

**Comment by stevemcc** [comment]
Appears to be this bug: https://github.com/supercollider/supercollider/pull/4855

Feel free to close this issue, sorry for the noise :)

**Comment by lvm** [comment]
Will leave this open until they fix it, in case anyone else comes reporting the same thing :-)

**Comment by lvm** [comment]
fixed in upstream.
