### ISSUE TITLE
Build script that installs packages?

### ISSUE THREAD

**Issue by Juul** [lvm/build-supercollider#26]
It would be a really good idea to warn the user when you build script wants to modify the system. That's not a nice surprise.

**Comment by lvm** [comment]
They are callede dependencies. It's not a surprise.

**Comment by Juul** [comment]
`apt -y install` is dangerous. It can cause packages to be removed. Calling something "build-<foo>" and the first thing it does is modify your system is not expected. If it was called "install-supercollider" it would be less of a problem. As it is your script risks damaging the users system.

**Comment by lvm** [comment]
👍
