### ISSUE TITLE
Requires emacs to compile

### ISSUE THREAD

**Issue by yaxu** [lvm/build-supercollider#3]
Due to `-DSC_EL=ON` in the build script, if emacs isn't installed, the compile will fail.
A quick solution would be to add emacs to the apt install..

**Comment by lvm** [comment]
i see. ~i assumed everyone would install a proper editor when setting up their computers.~ 
Probably the best solution would be to revert this flag, to avoid downloading unwanted dependencies.

**Comment by yaxu** [comment]
I think it's fine to download emacs, then it works for everyone (with the vim flag also on, it seems that doesn't cause build problems). People can edit the script if they want to be efficient.
As an aside the README contains info that beginners find confusing. Ok for me to move non-essential info out, focussing on the four-line install?

**Comment by lvm** [comment]
Fair enough. Also, thanks for moving the _extra_ stuff from the readme to another file, thought of doing it today but got entangled in work-stuff :-)
