### ISSUE TITLE
No 3.11 branch on https://github.com/supercollider/sc3-plugins

### ISSUE THREAD

**Issue by 0atman** [lvm/build-supercollider#9]
Script dies because sc3-plugins has no 3.11 branch.

I changed the value to 3.10 (as that branch does exist) and it worked :ok_hand:

**Comment by lvm** [comment]
fixed b6513d1433f4ed52685863b21344fe60db410869

FWIW, there's no need to re-compile sc3-plugins, but thanks for notifying.

**Comment by 0atman** [comment]
Nice one
